security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      stateless:  false
      anonymous: true
      guard:
        authenticators:
          - App\Security\Guard\LoginFormAuthenticator
      logout:
        path: app_logout
