security:
  role_hierarchy:
    ROLE_USER:
    ROLE_LIBRARY_USER: ['ROLE_USER']
    ROLE_PUBLISHER_USER: ['ROLE_USER']
    ROLE_ADMIN: ['ROLE_USER']
    ROLE_SUPER_ADMIN: ['ROLE_ADMIN', 'ROLE_ALLOWED_TO_SWITCH']
